### ISSUE TITLE
[Request] v10 compatibility

### ISSUE THREAD

**Issue by Eagle0600** [MAClavell/No-Token-Vision-Animation#2]
Hi, do you intend to continue support for this module into Foundry v10?

**Comment by MAClavell** [comment]
Just an FYI, I've finally gotten around to starting to update to v10. There have been some API changes which broke my previous implementation approach and are preventing any non-intrusive implementation ideas I have. The update will probably be delayed until I can get this figured out :(

**Comment by MAClavell** [comment]
Fixed in v1.4.0
